#:kivy 2.1.0
<PlotTestPage>:
    figure_wgt:figure_wgt
    legend_wgt:legend_wgt
    BoxLayout:
        size_hint_y: 0.1
        pos_hint: {"top":1}
        orientation: "vertical"
        id: layout
        MDLabel:
            halign: "center"
            text: "PLOT"
    BoxLayout:
        size_hint_y: 0.9
        orientation:'vertical'
        BoxLayout:
            size_hint_y:0.2
            Button:
                text:"Back"
                on_release:root.back_to_choose_menu()
            Button:
                text:"Home"
                on_release:root.home()
            ToggleButton:
                group:'touch_mode'
                state:'down'
                text:"Pan Mode" 
                on_release:
                    root.set_touch_mode('pan')
                    self.state='down'
            ToggleButton:
                group:'touch_mode'
                text:"Cursor Mode"  
                on_release:
                    root.set_touch_mode('cursor')
                    self.state='down'
        BoxLayout:
            MatplotFigure:
                id:figure_wgt
            LegendRv:
                id:legend_wgt
                figure_wgt:figure_wgt
                size_hint_x:0.2
